# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eas/Projects/blub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eas/Projects/blub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eas/Projects/blub/CMakeFiles /home/eas/Projects/blub/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eas/Projects/blub/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blub

# Build rule for target.
blub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blub
.PHONY : blub

# fast build rule for target.
blub/fast:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/build
.PHONY : blub/fast

src/controller.o: src/controller.cpp.o

.PHONY : src/controller.o

# target to build an object file
src/controller.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/controller.cpp.o
.PHONY : src/controller.cpp.o

src/controller.i: src/controller.cpp.i

.PHONY : src/controller.i

# target to preprocess a source file
src/controller.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/controller.cpp.i
.PHONY : src/controller.cpp.i

src/controller.s: src/controller.cpp.s

.PHONY : src/controller.s

# target to generate assembly for a file
src/controller.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/controller.cpp.s
.PHONY : src/controller.cpp.s

src/game/entities/camera.o: src/game/entities/camera.cpp.o

.PHONY : src/game/entities/camera.o

# target to build an object file
src/game/entities/camera.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/camera.cpp.o
.PHONY : src/game/entities/camera.cpp.o

src/game/entities/camera.i: src/game/entities/camera.cpp.i

.PHONY : src/game/entities/camera.i

# target to preprocess a source file
src/game/entities/camera.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/camera.cpp.i
.PHONY : src/game/entities/camera.cpp.i

src/game/entities/camera.s: src/game/entities/camera.cpp.s

.PHONY : src/game/entities/camera.s

# target to generate assembly for a file
src/game/entities/camera.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/camera.cpp.s
.PHONY : src/game/entities/camera.cpp.s

src/game/entities/player.o: src/game/entities/player.cpp.o

.PHONY : src/game/entities/player.o

# target to build an object file
src/game/entities/player.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/player.cpp.o
.PHONY : src/game/entities/player.cpp.o

src/game/entities/player.i: src/game/entities/player.cpp.i

.PHONY : src/game/entities/player.i

# target to preprocess a source file
src/game/entities/player.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/player.cpp.i
.PHONY : src/game/entities/player.cpp.i

src/game/entities/player.s: src/game/entities/player.cpp.s

.PHONY : src/game/entities/player.s

# target to generate assembly for a file
src/game/entities/player.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entities/player.cpp.s
.PHONY : src/game/entities/player.cpp.s

src/game/entity.o: src/game/entity.cpp.o

.PHONY : src/game/entity.o

# target to build an object file
src/game/entity.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entity.cpp.o
.PHONY : src/game/entity.cpp.o

src/game/entity.i: src/game/entity.cpp.i

.PHONY : src/game/entity.i

# target to preprocess a source file
src/game/entity.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entity.cpp.i
.PHONY : src/game/entity.cpp.i

src/game/entity.s: src/game/entity.cpp.s

.PHONY : src/game/entity.s

# target to generate assembly for a file
src/game/entity.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/game/entity.cpp.s
.PHONY : src/game/entity.cpp.s

src/logic/chunk.o: src/logic/chunk.cpp.o

.PHONY : src/logic/chunk.o

# target to build an object file
src/logic/chunk.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/chunk.cpp.o
.PHONY : src/logic/chunk.cpp.o

src/logic/chunk.i: src/logic/chunk.cpp.i

.PHONY : src/logic/chunk.i

# target to preprocess a source file
src/logic/chunk.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/chunk.cpp.i
.PHONY : src/logic/chunk.cpp.i

src/logic/chunk.s: src/logic/chunk.cpp.s

.PHONY : src/logic/chunk.s

# target to generate assembly for a file
src/logic/chunk.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/chunk.cpp.s
.PHONY : src/logic/chunk.cpp.s

src/logic/map.o: src/logic/map.cpp.o

.PHONY : src/logic/map.o

# target to build an object file
src/logic/map.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/map.cpp.o
.PHONY : src/logic/map.cpp.o

src/logic/map.i: src/logic/map.cpp.i

.PHONY : src/logic/map.i

# target to preprocess a source file
src/logic/map.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/map.cpp.i
.PHONY : src/logic/map.cpp.i

src/logic/map.s: src/logic/map.cpp.s

.PHONY : src/logic/map.s

# target to generate assembly for a file
src/logic/map.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/map.cpp.s
.PHONY : src/logic/map.cpp.s

src/logic/model.o: src/logic/model.cpp.o

.PHONY : src/logic/model.o

# target to build an object file
src/logic/model.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/model.cpp.o
.PHONY : src/logic/model.cpp.o

src/logic/model.i: src/logic/model.cpp.i

.PHONY : src/logic/model.i

# target to preprocess a source file
src/logic/model.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/model.cpp.i
.PHONY : src/logic/model.cpp.i

src/logic/model.s: src/logic/model.cpp.s

.PHONY : src/logic/model.s

# target to generate assembly for a file
src/logic/model.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/logic/model.cpp.s
.PHONY : src/logic/model.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderer/renderer.o: src/renderer/renderer.cpp.o

.PHONY : src/renderer/renderer.o

# target to build an object file
src/renderer/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.cpp.o

src/renderer/renderer.i: src/renderer/renderer.cpp.i

.PHONY : src/renderer/renderer.i

# target to preprocess a source file
src/renderer/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.cpp.i

src/renderer/renderer.s: src/renderer/renderer.cpp.s

.PHONY : src/renderer/renderer.s

# target to generate assembly for a file
src/renderer/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/blub.dir/build.make CMakeFiles/blub.dir/src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... blub"
	@echo "... edit_cache"
	@echo "... src/controller.o"
	@echo "... src/controller.i"
	@echo "... src/controller.s"
	@echo "... src/game/entities/camera.o"
	@echo "... src/game/entities/camera.i"
	@echo "... src/game/entities/camera.s"
	@echo "... src/game/entities/player.o"
	@echo "... src/game/entities/player.i"
	@echo "... src/game/entities/player.s"
	@echo "... src/game/entity.o"
	@echo "... src/game/entity.i"
	@echo "... src/game/entity.s"
	@echo "... src/logic/chunk.o"
	@echo "... src/logic/chunk.i"
	@echo "... src/logic/chunk.s"
	@echo "... src/logic/map.o"
	@echo "... src/logic/map.i"
	@echo "... src/logic/map.s"
	@echo "... src/logic/model.o"
	@echo "... src/logic/model.i"
	@echo "... src/logic/model.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/renderer/renderer.o"
	@echo "... src/renderer/renderer.i"
	@echo "... src/renderer/renderer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

